app = "app-autumn-water-7457"

[build]
  image = "dartw/app:stage"

[env]
  PORT = "3000"
  BUN_ENV = "stage"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
