app = "app-wild-dust-1031"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.stage"

[env]
  BUN_ENV = "stage"
  PORT = "3000"
  BASE_URL = "https://app-wild-dust-1031.fly.dev"
  DATABASE_URL = "placeholder"  
  RATE_LIMIT_MAX = "placeholder"  
  RATE_LIMIT_WINDOW = "placeholder" 
  SONAR_TOKEN = "placeholder"   

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "30s"
    timeout = "15s" 
    grace_period = "60s" 
    method= "GET"       
    path = "/"  
